"""Class to format docstrings in Markdown"""

from inspect import getsource, getfullargspec
import sys
from time import strftime
from files import find_functions, DataTypes
from settings import CONFIG


class FormattedText:
    """Class to format docstrings in Markdown"""

    url = "https://github.com/j-lucas-d/DocString-to-Markdown"
    name = "DocString-to-Markdown"

    def __init__(self):
        self.formatted_lines = []

    def _process_arguments(self, data: getfullargspec):
        """Creates Markdown for the arguments list

        Args:
            data: Object containing argument data

        Returns:
            Markdown formatted text
        """

        self.formatted_lines.append("**Arguments**")
        if data.args:
            for arg in data.args:
                if arg not in ("self", "cls"):
                    self.formatted_lines.append(f"- {arg}")
                    if data.annotations.get(arg):
                        self.formatted_lines[
                            -1
                        ] += f" ({data.annotations.get(arg).__name__})"

        self.formatted_lines.append("\n**Returns**: ")
        if data.annotations.get("return"):
            self.formatted_lines.append(data.annotations["return"].__name__)
        else:
            self.formatted_lines.append("None")

        self.formatted_lines.append("\n")

    def _document_functions(
        self,
        name: str,
        docstring: str,
        arguments: getfullargspec,
        source: str,
        _path: str = "",
    ):
        if not docstring:
            docstring = "!!! WARNING: NO DOCSTRING FOUND !!!"

        self.formatted_lines.append(f"### FUNCTION: {_path}{name}\n")
        self.formatted_lines.append(f"{docstring}\n")
        self._process_arguments(arguments)
        self.horizontal_rule()

        if CONFIG.show_source:
            self.formatted_lines.append(f"```python\n{source}```\n")

    def _document_classes(
        self, name: str, docstring: str, arguments: getfullargspec, _path: str = ""
    ):
        if not docstring:
            docstring = "!!! WARNING: NO DOCSTRING FOUND !!!"

        self.formatted_lines.append(f"### CLASS: {name}\n")
        self.formatted_lines.append(f"{docstring}\n")
        # TODO: Add arguments?

    def format_docs(self, data: DataTypes, filter_module: str, _path: str = ""):
        """Creates formatted Markdown text for the classes and functions
        provided

            Args:
                data: DataTypes instance containing function objects
                filter_module: Name of module to inspect. All others are ignored
                _path: Do not use. Used within the function to track the module path

            Returns:
                Markdown formatted text
        """

        if _path:
            _path += "."

        # Functions first
        for func in data.functions:
            self._document_functions(
                name=func.__name__,
                docstring=func.__doc__,
                arguments=getfullargspec(func),
                source=getsource(func),
                _path=_path,
            )
            if not func.__doc__:
                print(
                    f"Warning: No docstring found for: {func.__name__}!",
                    file=sys.stderr,
                )

        # Classes second
        for cls in data.classes:
            self._document_classes(
                name=cls.__name__,
                docstring=cls.__doc__,
                arguments=getfullargspec(cls),
                _path=_path,
            )
            if not cls.__doc__:
                print(
                    f"Warning: No docstring found for: {cls.__name__}!",
                    file=sys.stderr,
                )

            # Recurse into class to find subclasses and methods
            cls_data = find_functions(cls, filter_module)
            size = len(self.formatted_lines)
            self.format_docs(cls_data, filter_module, _path=_path + cls.__name__)
            if len(self.formatted_lines) == size:
                # Only add a rule if the class had no methods
                self.horizontal_rule()

    def horizontal_rule(self):
        """Creates a horizontal rule"""
        self.formatted_lines.append("\n---\n")

    def format_footer(self):
        """Creates a footer and the end of each document

        Returns:
            Markdown formatted text
        """
        timestamp = strftime("%d %B %Y")
        self.formatted_lines.append(
            f"\n\n*Automatically generated by [{self.name}]({self.url}) {timestamp}*\n"
        )

    def format_title(self):
        """Creates a Markdown formatted title and description

        Returns:
            Markdown formatted text
        """
        self.formatted_lines.append(f"# {CONFIG.title}\n\n{CONFIG.description}\n\n")

    def format_filename(self, mod, path: str):
        """Creates a Markdown formatted module header

        Args:
            mod: Module object
            path: Path to module

        Returns:
            Markdown formatted text
        """
        self.formatted_lines.append(
            f"## FILE: [{mod.__name__}]({path})\n\n{mod.__doc__}\n"
        )

    def add_index(self, name: str, docstring: str):
        """Adds a bulleted line to index Markdown files"""
        self.formatted_lines.append(f"- [{name}.md]({name}.md): {docstring}\n")

    def formatted_text(self):
        """Returns collected text as a string"""
        return "\n".join(self.formatted_lines)
